### ISSUE TITLE
Using on frequencies under 100Mhz.

### ISSUE THREAD

**Issue by sandmix** [hannes-hochreiner/sensor-node#1]
Hi, maybe you know what changes need to be done so I can use SI4012 around 50Mhz. Thanks.

**Comment by hannes-hochreiner** [comment]
The Si4012 is specified for a frequency interval of 27–960 MHz. Hence, you should be able to use it at 50MHz. You will have to adjust the antenna. There are some references in the README that should help you calculate the required antenna parameters.
